easystats/insight

.gitattributes

:wave: Hi @strengejacke,
I've noticed that `easystats` is tagged as mostly HTML by [GitHub's linguist](https://github.com/github/linguist), I've followed the [overriding instructions](https://github.com/github/linguist#overrides) which should let the repo be tagged as pure R.

Correct identification of easystats as R package

---

README.md
README.rmd

clicking on the github actions badge on the readme leads to a SVG rather than the report page.

fix github action badge link

---

R/standardize_names.R
tests/testthat/test-standardize_names.R

As I had suspected, `broom` doesn't actually have any convention about the CI column.
So I would prefer to default to `conf.level`, which is more in line with `tidymodels`'s argument naming.

changing convention; cf. https://github.com/tidymodels/broom/issues/984

---

R/find_variables.R
man/find_variables.Rd

Changed the list to markdown style.
Alphabetical order after `reponse` and `conditional`

find_variables doc to markdown style

---

R/get_predicted_ci.R
tests/testthat/test-get_predicted.R

Today I was having trouble with `get_predicted`: it was taking a ton of time to produce estimates for a model with about 50K observations. So I decided to do a bit of profiling. It turns out that the vast majority of the time was spent on the “sandwich” multiplication.
In this PR, I introduce a simple matrix algebra trick for the sandwich computation, which yields roughly 1000x speedup in computation and 1000x reduction in memory load.
To begin, let’s create a variance-covariance matrix and a large model matrix by stacking `mtcars` multiple times:
``` r
library(bench)
mod <- lm(mpg ~ factor(cyl) + hp + drat, mtcars)
mtbig <- do.call("rbind", lapply(1:500, \(x) mtcars))
mm <- model.matrix(mod, data = mtbig)
vcovmat <- vcov(mod)
```
Before running the benchmark, let’s convince ourselves …

algebra trick for much faster SEs in `get_predicted`

---

R/get_predicted.R
man/get_predicted.Rd
tests/testthat/test-get_predicted.R

This is a PR to address issue #431  
I included a bunch of new tests, and what feels like "conservative" warnings and errors.
From my perspective, the main thing that still needs to be hashed out is what to do with the current `predict="response"` argument value. In Issue #432, there are some suggestions for different naming convention. At this stage, I would actually advocate removing it altogether for the reasons stated in the other issue. 
Any feedback would be much appreciated! I'm happy to make any change you deem necessary.

get_predicted: `type` vs. `predict` disambiguation

---

R/get_predicted.R

Fixing a bug that I introduced myself. `get_predicted.default` should call `predict` using the `newdata` argument instead of `data`.

bugfix: get_predicted uses newdata

---

R/get_predicted.R
R/get_predicted_ci.R
tests/testthat/test-brms.R

Fix for https://github.com/easystats/insight/issues/471
TODO:

WIP: get_predicted.brmsfit supports categorical dv

---

R/clean_names.R

This solves https://github.com/easystats/insight/issues/480: clean_names not work when bSplines (from the package splines2) are used in (g)lm models

add bSpline to patterns in .remove_pattern_from_names

---

R/helper_functions.R

Follow up on comments from here: https://github.com/easystats/insight/pull/484#
The new flag/indexing strategy improves the speed of `get_data` by 100x in a naive benchmark I just ran:
New:
```
expression         min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
<bch:expr>    <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
1 get_data(mod)   59.3ms   78.6ms      13.8    57.3MB        0     3     0
```
Old:
```
expression      min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
<bch:expr>    <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
1 get_data(mod) 9.61s  9.61s     0.104     235MB     1.14     1    11      9.61s
```

speed: .is_empty_object

---

R/get_predicted_ci.R
tests/testthat/test-lmer.R

I’m not sure the first problem raised here <https://github.com/easystats/insight/issues/494> can be fixed in `insight`, but this PR raise a slightly more informative warning and avoids a hard stop:
``` r
library(lme4)
mod <- lmer(
weight ~ 1 + Time + I(Time^2) + Diet + Time:Diet + I(Time^2):Diet + (1 + Time + I(Time^2) | Chick),
data = ChickWeight)
newdata <- ChickWeight[ChickWeight$Time %in% 0:10 & ChickWeight$Chick %in% c(1, 40), ]
newdata$Chick[newdata$Chick == "1"] <- NA
get_predicted(mod, data = newdata, include_random = FALSE)
```

get_predicted_ci: warning on non-conformable matrices

---

NEWS.md
R/find_formula.R
tests/testthat/test-gls.R
tests/testthat/test-lme.R

Close #482 
```r
library(nlme)
cr <- corAR1(form = ~ 1 | Mare)
fm1 <- lme(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
correlation = cr)
insight::find_formula(fm1)
$conditional
follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time)
<environment: 0x0000024c7b2e5e28>
$correlation
~1 | Mare
attr(,"class")
[1] "insight_formula" "list"           
fm2 <- lme(follicles ~ sin(2*pi*Time) + cos(2*pi*Time), Ovary,
correlation = corAR1(form = ~ 1 | Mare))
insight::find_formula(fm2)
$conditional
follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time)
<environment: 0x0000024c6fa4b718>
$correlation
~1 | Mare
<environment: 0x0000024c6fa4b718>
attr(,"class")
[1] "insight_formula" "list" 
```

find_formula: fix when arg "correlation" defined outside of lme()

---

R/get_predicted_se.R
R/get_varcov.R
R/get_varcov_sandwich.R
man/get_varcov.Rd
tests/testthat/test-get_data.R
tests/testthat/test-get_varcov.R
tests/testthat/test-zeroinfl.R

Currently only works for `get_varcov.default()`
Question/Problem: All `get_varcov.CLASS()` methods accept `...`. This means that when `sandwich` does not support a model, the `vcov` argument will be absorbed silently and return an IID var-cov without any warning.
Do we have to introduce explicit warnings in every single method where `sandwich` doesn't work? What is the most elegant way to do that?

WIP: get_varcov(): vcov and vcov_args arguments

---

R/get_varcov.R
tests/testthat/test-get_varcov.R

Current, the `verbose` argument does not suppress warnings from `.check_vcov_args`

get_varcov(verbose) and deprecated robust argument

---

R/export_table.R

Related to https://github.com/easystats/parameters/pull/722: in html, the table footnotes are separated by `<br/>`, which needs to be formatted to break lines

Format html code in table footer

---

NEWS.md
R/format_bf.R
R/format_table.R
man/format_bf.Rd
tests/testthat/test-format.R

_Originally posted #589_
Since BFs are translational, BF<sub>A vs B</sub> / BF<sub>C vs B</sub> = BF<sub>A vs C</sub>
However, with the current default behavior of `format_bf(..., exact = FALSE)` information is lost and this property of BFs cannot be used.
(I just saw “BF \> 1000” in a paper along with other `{report}` text, so I’m tracing this back to here.)
``` r
library(bayestestR)
m1 <- lm(mpg ~ 1, mtcars)
m2 <- lm(mpg ~ hp, mtcars)
m3 <- lm(mpg ~ cyl, mtcars)
Bfs <- bayesfactor_models(m2, m3, denominator = m1)
```
**Old behavior**: Can’t infer that `m3` is supported over `m2` - 
``` r
format_bf(exp(Bfs$log_BF))
#> [1] "BF > 1000" "BF > 1000" "BF = 1.00"
```
**New behavior**: Can infer that `m3` is supported over `m2` - 
``` r
format_bf(exp(Bfs$log_BF))
#> [1] "BF = …
```

Format bf exact

---

R/get_predicted_args.R

`get_predicted()` raises an informative message when there is a matrix column in the terms. However, sometimes we supply our own `data`, and the message is still raised even if that `data` does *not* include a matrix column.

scale message

---

R/find_formula.R

Problem: sometimes users assign a formula to an object, and then feeds that object to the formula parameter of a fitting function. In the `selection` model type, this poses problems because we extract the formula from the model call, and the apply `stats::as.formula` directly to that. But if the call includes a symbol rather than the formula itself, this breaks. We need to evaluate the symbol before calling `as.formula`.
This is a simple PR with a `tryCatch` and a 2nd attempt with `eval()`

`find_formula` evaluates symbol in call

---

R/utils_object.R

`is_empty_object()` is extremely slow when applied to data frames, and this in turn slows down a bunch of other functions like `get_data()`. (Also see: https://github.com/vincentarelbundock/modelsummary/issues/479)
Currently, the function does this:
```r
x <- x[, !sapply(x, function(i) all(is.na(i))), drop = FALSE]
flag_empty <- all(rowSums(is.na(x)) == ncol(x))
```
The first line assigns `x` to the subset of columns with at least one non-`NA` value. The second line checks if all rows of that subset are completely `NA`. But by construction, the second check should always pass if we have at least one column with at least one non-`NA` value. So it's redundant and wasteful.
Am I misunderstanding the logic?
If this is right, then this PR improves the situation by looping over columns and …

Faster `is_empty_object`

---

DESCRIPTION
NEWS.md
R/format_message.R
man/format_message.Rd
man/get_predicted.Rd
man/get_predicted_ci.Rd

This PR adds minor formatting options to `format_message()`:
- `{.b boldtext}`
- `{.i emphasizetext}`
- `{.url url.toweb.site}`
- `{.pkg easystats}`
Example:
```r
x <- "This is a very long string that allow {.b bold} formatting"
cat(format_message(x))
```
Limitations: it's hard to detect the "real" (without format tags) streng length for line breaks. Thus, it can happen that lines are wrapped at an earlier length than expected. Furthermore, if you have multiple words in a format tag (`{.b one two three}`), a line break might occur in this tag, and the formatting no longer works.

format_message accepts tokens

---

R/utils_object.R
tests/testthat/test-object_has_helpers.R

``` r
object_has_rownames <- function(x) {
if (!is.data.frame(x)) {
stop("Only dataframe objects are allowed.", call. = FALSE)
}
!identical(as.character(seq_len(nrow(x))), rownames(x))
}
new_object_has_rownames <- function(x) {
if (!is.data.frame(x)) {
stop("Only dataframe objects are allowed.", call. = FALSE)
}
!all(is.numeric(attributes(x)$row.names))
}
out <- list()
for (i in 1:100000) {
out[[i]] <- iris
}
out <- data.table::rbindlist(out)
nrow(out)
#> [1] 15000000
bench::mark(
old = object_has_rownames(out),
new = new_object_has_rownames(out)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median   `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>       <dbl> <bch:byt>    <dbl>
#> 1 old …
```

Improve performance of `object_has_rownames()` 

---

R/utils_object.R
tests/testthat/test-object_has_helpers.R

Make `object_has_rownames()` stricter (but still more performant), cf #652 :
``` r
object_has_rownames <- function(x) {
if (!is.data.frame(x)) {
stop("Only dataframe objects are allowed.", call. = FALSE)
}
!identical(as.character(seq_len(nrow(x))), rownames(x))
}
new_object_has_rownames <- function(x) {
if (!is.data.frame(x)) {
stop("Only dataframe objects are allowed.", call. = FALSE)
}
!identical(attributes(x)$row.names, 1:nrow(x))
}
out <- list()
for (i in 1:100000) {
out[[i]] <- iris
}
out <- data.table::rbindlist(out)
nrow(out)
#> [1] 15000000
bench::mark(
old = object_has_rownames(out),
new = new_object_has_rownames(out)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc …
```

Fix `object_has_rownames()`

---

R/find_formula.R

Close issue #658. The idea, as told there, is to do `fm <- formula(x$terms)` instead of `fm <- eval(x$call$fixed) `, but this would need to include `importFrom("stats", formula)` in the NAMESPACE, and since there is no `importFrom` there, I assumed you prefer not use them. Therefore, instead of using `formula(....)`, I wrote the  code of `stats:::formula.terms` there.

fix issue 658 by reproducing formula function

---

DESCRIPTION
NEWS.md
R/format_table.R
man/format_table.Rd
tests/testthat/test-format_table.R

``` r
m <- brms::brm(mpg ~ wt, data=mtcars, prior = brms::set_prior("normal(0, 1)", class = "b"), refresh=0)
#> Compiling Stan program...
#> Start sampling
param <- parameters::parameters(m, test=c("pd", "BF"))
#> Warning: Bayes factors might not be precise.
#> For precise Bayes factors, sampling at least 40,000 posterior samples is recommended.
insight::format_table(param, stars="pd")
#>     Parameter   Component Median         95% CI      pd  Rhat     ESS       BF
#> 1 (Intercept) conditional  32.30 [27.68, 36.28] 100%*** 1.001 2272.00 1.73e+08
#> 2          wt conditional  -3.81 [-4.96, -2.39] 100%*** 1.000 2163.00 1.60e+03
#> 3       sigma       sigma   3.47 [ 2.65,  4.83] 100%*** 1.001 1779.00 4.36e+09
```
<sup>Created on 2022-10-03 by the [reprex …

Allow to show stars only for specific column

---

DESCRIPTION
NEWS.md
R/get_datagrid.R
man/get_datagrid.Rd
tests/testthat/test-get_datagrid.R

The current behaviour of the `at` argument is confusing and not working as described in the docs.
``` r
get_datagrid(iris, at = list(c(Sepal.Length = c(2, 4), Species = "setosa")))
#> Error in at[sapply(x[names(at)], is.factor)]: invalid subscript type 'list'
at <- c("Sepal.Length = c(3, 5)", "Species = c('versicolor', 'virginica')")
get_datagrid(iris, at = at)
#>   Sepal.Length    Species Sepal.Width Petal.Length Petal.Width
#> 1            3 versicolor    3.057333        3.758    1.199333
#> 2            5 versicolor    3.057333        3.758    1.199333
#> 3            3  virginica    3.057333        3.758    1.199333
#> 4            5  virginica    3.057333        3.758    1.199333
```
The new approach converts the passed list into a character vector: …

make at argument more intuitive

---

DESCRIPTION
NEWS.md
R/get_datagrid.R
tests/testthat/test-get_datagrid.R

Edgecase: when 'k' is a variable in GAM's s(), datagrid fails

---

DESCRIPTION
R/get_modelmatrix.R
R/get_predicted_se.R
tests/testthat/test-get_datagrid.R
tests/testthat/test-get_modelmatrix.R
tests/testthat/test-get_predicted.R
tests/testthat/test-lmer.R

This PR comments out dangerous code in the calculation of SEs for predicted values. I think it is very important to merge this as soon as possible because the current version of `insight` produces incorrect numerical results.
``` r
set.seed(12345)
n <- 500
x <- sample(1:3, n, replace = TRUE)
y <- rnorm(n)
z <- ifelse(x + y + rlogis(n) > 1.5, 1, 0)
dat <- data.frame(x = factor(x), y = y, z = z)
m <- glm(z ~ x + y, family = binomial, data = dat)
nd <- head(dat, 2)
predict(m, type = "link", newdata = nd, se.fit = TRUE)$se.fit
1         2 
0.1924812 0.2117471 
get_predicted(m, data = head(dat, 2), ci = 0.95, predict = "link") |> data.frame()
Predicted        SE     CI_low   CI_high
1 -0.1884105 0.2948762 -0.7663572 0.3895363
2  1.6547188 0.3374601  0.9933091 2.3161285
```

bug: get_predicted_se with incomplete MM

---

R/compute_variances.R

`thetaf` was renamed to `psi` in glmmTMB 1.1.5 (https://github.com/glmmTMB/glmmTMB/pull/871). Keep supporting the old name just in case.

Fix variance for Tweedie with glmmTMB >= 1.1.5

---

R/get_data.R
tests/testthat/test-get_data.R

`complete.cases()` eliminated rows when missing values in non-model columns.

bugfix and test: get_data(additional_variables = TRUE)

---

DESCRIPTION
NEWS.md
R/format_number.R
R/format_value.R
man/format_value.Rd
tests/testthat/test-format.R
tests/testthat/test-htest.R

options for `format_value()` : drop leading 0, minus and plus signs

---

R/utilities.R

I realised in https://github.com/easystats/datawizard/pull/384 that `trim_ws()` uses a lot of memory compared to its base equivalent. Using `perl = TRUE` reduces it:
``` r
new_trim_ws <- function(x) {
gsub("^\\s+|\\s+$", "", x, perl = TRUE)
}
test <- rep("  Some text. ", 10000)
bench::mark(
base = trimws(test),
old = insight::trim_ws(test),
new = new_trim_ws(test),
iterations = 1000
)
#> # A tibble: 3 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 base         4.99ms   5.44ms      168.  156.34KB    0.337
#> 2 old          6.06ms   6.68ms      134.    1.33MB    0.135
#> 3 new          3.97ms   4.72ms      179.   78.17KB    0.359
```
<sup>Created on 2023-03-19 with [reprex …

Small memory improvement for `trim_ws()` 

---

R/backports.R
R/find_response.R
R/get_datagrid.R
R/null_model.R
R/utils_get_data.R

So remove the backported copy for R 3.5.

`str2lang()` available from `R 3.6`

---

R/utils_get_data.R

Small addition to make sure that any offset column is included as part of the `get_data` return.
I'm not sure how common the problem is, but it can occur when **fixest** models are called within another function and so the call environment is masked (thus requiring manual retrieval via the model frame). 
I first noticed it because offsets were not appearing as part of my **etwfe** package, which constructs a `fixest::feols()` call internally (https://github.com/grantmcdermott/etwfe/issues/28). But here's a much simpler MWE.
```r
feols2 = function(fml, data, ...) {
fixest::feols(fml = fml, data = data, ...)
}
m1 = fixest::feols(mpg ~ hp, data = mtcars, offset = ~cyl) # native behaviour as sanity check
m2 =        feols2(mpg ~ hp, data = mtcars, offset = ~cyl)
```
Current behaviour (note …

Include offset in get_data

---

DESCRIPTION
NEWS.md
R/get_data.R
R/get_predicted.R
tests/testthat/test-get_data.R
tests/testthat/test-get_predicted.R

The commit messages should explain the issue, and I've added a comment explaining the `enclos` issue, since it's definitely not obvious.
I've also added tests for three cases:
* data is present in the local environment
* data is in a different environment
* data is in a different environment, and another object of the same name is in the parent environment
All of these fail without the fix. But it's worth adding more if you can think of additional cases, since this is definitely easy to mess up. Are there other cases you'd expect to cause problems?

Fix #760, so `get_data()` can fetch from the correct environment, and add tests

---

R/format_table.R
man/export_table.Rd
man/format_table.Rd
tests/testthat/test-get_predicted.R

Fixes #762 
``` r
library(report)
x <- t.test(mtcars$mpg ~ mtcars$am)
report_table(x)[14:16]
#> Cohen's d |  Cohen's d  CI
#> --------------------------
#> -1.41     | [-2.26, -0.53]
as.data.frame(report_table(x))[14:16]
#>    Cohens_d Cohens_d_CI_low Cohens_d_CI_high
#> 1 -1.411046       -2.260021       -0.5342257
format_table(as.data.frame(report_table(x))[14:16])
#>   Cohen's d  Cohen's d  CI
#> 1     -1.41 [-2.26, -0.53]
```
<sup>Created on 2023-05-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`format_table()`: Change `Cohens_d CI` to `Cohen's d CI`

---

R/get_data.R
tests/testthat/test-get_data.R

Dangerous `get_data()` behavior with `fixest` models and name conflicts

---

DESCRIPTION
NEWS.md
R/check_if_installed.R
R/get_predicted_bayesian.R
man/check_if_installed.Rd
tests/testthat/test-check_if_installed.R

`check_if_installed()` now automatically checks the package DESCRIPTION file to determine the correct minimum version required.
---
Closes #793 and closes #794

`check_if_installed()` now automatically determines the correct minimum version

---

DESCRIPTION
R/find_terms.R
R/find_transformation.R
R/get_transformation.R
tests/testthat/test-find_terms.R
tests/testthat/test-find_transformation.R

`find_transformation` incorrectly detects power transformations

---

DESCRIPTION
NEWS.md
R/get_predicted.R
R/get_predicted_ci.R
man/get_predicted.Rd
man/get_predicted_ci.Rd
man/get_transformation.Rd
tests/testthat/test-find_transformation.R

Differences between get_predicted and get_predicted_ci for mixed models

---

DESCRIPTION
NEWS.md
R/color_if.R
R/find_predictors.R
man/color_if.Rd
tests/testthat/test-plm.R
tests/testthat/test-survfit.R

`find_predictors()` with multiple `strata()` variables in `clogit()`

---

tests/testthat/test-backticks.R
tests/testthat/test-coxme.R
tests/testthat/test-coxph.R
tests/testthat/test-fixest.R

Fixes https://github.com/easystats/easystats/issues/388

Use withr to not change global state

---

R/is_multivariate.R
R/model_info.R
inst/WORDLIST
man/model_info.Rd
tests/testthat/test-gam.R
tests/testthat/test-glmmTMB.R
tests/testthat/test-vgam.R

I thought I might as well update this here so that the ggeffects function can use `model_info` for everything including checking for multivariate models. Works for both `is_multivariate` and `model_info`.
Updated one test which which expected `is_multivariate == FALSE`, I imagine as a placeholder - it has two outcome variables.
I figure this is a cleaner solution but let me know if you'd rather leave as is.
strengejacke/ggeffects#432

Detect multivariate vgams/vglms

---

DESCRIPTION
NEWS.md
R/standardize_names.R
tests/testthat/test-marginaleffects.R

rename marginaleffects' `s.value` column name

---

DESCRIPTION
NEWS.md
tests/testthat/test-get_variance.R
tests/testthat/test-glmmTMB.R

There are two changes here:
1. account for the fact that Gaussian dispersion is parameterized as log-SD rather than log-variance now
2. change starting value for `theta` to avoid a singular fit (caused by slight changes in numerical stability due to Gaussian reparameterization)
also some minor spelling corrections (sorry)

updates for glmmTMB changes

---

R/get_varcov_sandwich.R
tests/testthat/test-get_varcov.R

Improves error messages when `vcov` argument is unrecognized. The previous error was unreadable because we were asking `sprintf` to insert a `NULL` value.

get_varcov: better error message on bad vcov value

---

DESCRIPTION
NEWS.md
R/export_table.R
R/get_datagrid.R
R/get_predicted.R
R/get_predicted_args.R
R/get_predicted_bayesian.R
R/get_predicted_fixedeffects.R
R/get_predicted_gam.R
R/get_predicted_methods.R
R/get_predicted_mixed.R
R/get_predicted_ordinal.R
R/get_predicted_zeroinfl.R
R/print_parameters.R
man/export_table.Rd
man/get_datagrid.Rd
man/print_parameters.Rd
tests/testthat/test-gam.R
tests/testthat/test-get_datagrid.R
tests/testthat/test-marginaleffects.R

https://github.com/easystats/easystats/issues/404

Rename `group`/`group_by` arguments into `by`

---

DESCRIPTION
NEWS.md
R/find_formula.R
R/find_predictors.R
R/helper_functions.R
tests/testthat/test-brms.R

`find_variables()` & `brms`: Distributional component variables missing

---

DESCRIPTION
NEWS.md
R/display.R
man/display.Rd
man/trim_ws.Rd

`display()` example loses linebreaks

---

DESCRIPTION
NEWS.md
R/export_table.R
man/export_table.Rd
tests/testthat/_snaps/windows/export_table.md
tests/testthat/test-export_table.R

Closes #951
> It's not set to auto, because sometimes a horizontal scrollbar is better than a split table, when it's just one column too wide.
_Originally posted by @strengejacke in https://github.com/easystats/insight/issues/951#issuecomment-2447096914_
The current implementation will never make a split that leaves a single column table.
``` r
z <- mtcars[1,] |> 
insight::export_table(table_width = NULL) |> 
strsplit(split = "\n") |> _[[1]]
nchar(z[1], type = "width")
#> [1] 68
mtcars[1:5,] |> 
insight::export_table(table_width = 67)
#>   mpg | cyl | disp |  hp | drat |   wt |  qsec | vs | am | gear | carb
#> ----------------------------------------------------------------------
#> 21.00 |   6 |  160 | 110 | 3.90 | 2.62 | 16.46 |  0 |  1 |    4 |    4
#> 21.00 |   6 |  160 | 110 | 3.90 | …
```

Allow `export_table()` to split to more than 3 tables

---

NEWS.md
R/format_value.R
man/format_value.Rd
tests/testthat/test-format.R

format_value() should consider "options(OutDec=',')" for separator formatting

---

R/find_parameter_zi.R
R/find_parameters.R
R/find_parameters_bayesian.R
R/find_parameters_gam.R
R/find_parameters_mfx.R
R/find_parameters_mixed.R
R/find_parameters_other.R
R/find_predictors.R
R/find_variables.R
man/find_interactions.Rd
man/find_parameters.BGGM.Rd
man/find_parameters.Rd
man/find_parameters.averaging.Rd
man/find_parameters.betamfx.Rd
man/find_parameters.emmGrid.Rd
man/find_parameters.gamlss.Rd
man/find_parameters.glmmTMB.Rd
man/find_parameters.zeroinfl.Rd
man/find_predictors.Rd
man/find_random.Rd
man/find_smooth.Rd
man/find_terms.Rd
man/find_variables.Rd
man/get_data.Rd
man/get_parameters.BGGM.Rd
man/get_parameters.Rd
man/get_parameters.betamfx.Rd
man/get_parameters.betareg.Rd
man/get_parameters.gamm.Rd
man/get_parameters.zeroinfl.Rd

Don't show "usage" for all classes (make docs clearer)

Reduce methods appearing in docs, to make docs clearer

---

R/find_terms.R
R/find_transformation.R
tests/testthat/test-find_terms.R
tests/testthat/test-find_transformation.R
tests/testthat/test-gamlss.R

Partial fail in new Box-Cox-handling in insight 0.99.0.15

---

DESCRIPTION
NEWS.md
R/get_datagrid.R
tests/testthat/test-get_datagrid.R

specified in `by` was not found in the data.

`get_datagrid()` gives a more informative error message when a variable

---

DESCRIPTION
NEWS.md
R/get_varcov.R

get_varcov() fails when brms models have monotonic effects

---

DESCRIPTION
NEWS.md
R/get_datagrid.R
tests/testthat/test-get_datagrid.R

`get_datagrid()` should include a dummy-weight variable for glmmTMB models

---

DESCRIPTION
NEWS.md
R/get_predicted_args.R

Fix get_predicted for multivariate (i.e., multiple outcomes) models

---

DESCRIPTION
R/get_predicted_args.R
R/get_predicted_bayesian.R

if user provided `dpars` argument, we just pass it to the `predict()`-function. we don't overwrite the `predict` argument, because this allows us to pass dpars to `posterior_predict()` - else, when dpars are provided via the `predict`-argument, we always set `predict = "expectation"`, thus, have no option to use dpars with `posterior_predictions()`.

Allow dpars-argument to be passed to predict-function
