README.Rmd, README.md, tests/testthat/test-brms.R, tests/testthat/test-glmmTMB.R, tests/testthat/test-response_data2.R
The 4 failing tests also failed locally due to the addition of the dispersion parameter and some changes in the cbind() return. Must now investigate the brms
=> fix glmmTMB and response_data2 tests

.gitignore, R/model_info.R, man/model_info.Rd
Minor renaming in model_info. 
However, these 2 tests fail in local:
```
-- 1. Failure: linkfun (@test-brms.R#210)  ------------------------------------------------------------------------------------
is.null(link_function(m2)) isn't false.
-- 2. Failure: linkfun (@test-brms.R#213)  ------------------------------------------------------------------------------------
is.null(link_function(m5)) isn't false.
```
=> model_info: is_bayes to is_bayesian

README.Rmd, README.md
Since the list of supported models is already rather long, we might switch to floating text instead of using a list? And I wrote out the function names, it's clearer,  I think.
=> Revise Readme

paper.md
Here are my thoughts on a clean, succinct JOSS-style manuscript that introduces the package. Feel free to keep, revise, or discard anything here you see fit. Thanks!
=> Updates to the JOSS manuscript

R/print_parameters.R
Take special note of changes on lines 23-24. Make sure this is still reflective of what you're trying to get across.
=> Several grammatical changes

R/find_statistic.R, R/is_model.R, tests/testthat/test-gam.R, tests/testthat/test-multinom.R
Minor edit to `find_statistic` function to properly handle `gam`, `nnest`, and `multinom` objects
=> find_statistic returns t-statistic for gam, nnest, and multinom objects

NEWS.md, R/find_statistic.R, R/get_parameters.R, R/get_variances.R, R/is_model.R, inst/WORDLIST, man/get_variance.Rd, tests/testthat/test-BayesFactorBF.R, tests/testthat/test-cpglmm.R, tests/testthat/test-nlmer.R
See my comment on this commit: https://github.com/easystats/insight/commit/2b085b2dd85ad7f45308a8c83775cb3aca1a9404
It will be better to run this check at the final stage in `fix_statistic`
=> fixing fix_statistic issue; adding more models

R/get_predicted.R
Following up on recent discussion, I think this is clearer and it also more closely aligns with stan/Bayes terminology of linpred, epred, and predict. Deprecating `"relation"` for now gives users time to change syntax.
=> Deprecate `predict = "relation"` in favor of `predict = "expectation"`.

R/check_if_installed.R, R/data_relocate.R, R/data_reshape.R, R/data_restoretype.R, R/export_table.R, R/find_predictors.R, R/get_predicted.R, R/get_predicted_ci.R, R/get_predicted_methods.R, tests/testthat/_snaps/rstanarm.md, tests/testthat/test-get_predicted.R, tests/testthat/test-rstanarm.R
=> adds tests for #375

R/format_p.R
APA now strongly recommends/requires exact p values unless p < .001.
=> Make digits="apa" compliant with APA 7th edition

R/get_parameters_emmeans.R, R/get_statistic.R, tests/testthat/test-emmeans.R
Related to https://github.com/easystats/parameters/issues/590
Replacing a convoluted way to get the test statistic + minor fix in pulling the estName
=> fix emmeans statistic and estName

R/get_predicted.R
Closes https://github.com/easystats/insight/issues/420
Closes https://github.com/easystats/insight/pull/421
=> Set `type` argument in `get_predicted.default()`

R/find_variables.R, man/find_variables.Rd
Applying `find_variables` to a model of class `fixest` produces a list with a `cluster` element, but this type of variable is undocumented. This is a one-line PR to add documentation.
``` r
library("insight")
library("fixest")
mod <- feols(mpg ~ hp | cyl, data = mtcars)
find_variables(mod)
```
<details style="margin-bottom:10px;">
<summary>
Standard output and standard error
</summary>
`/Users/vincent/Downloads/tmp_std_out_err.txt`
</details>
<details style="margin-bottom:10px;">
<summary>
Session info
</summary>
``` r
sessioninfo::session_info()
```
</details>
=> document find_variables cluster type

R/get_predicted_ci.R
This PR illustrates one of the strategies described in this thread: https://github.com/easystats/insight/issues/423
The problem is that feeding a `terms` to the `model.matrix` function drops factor levels if they are not present in the `data` argument. Feeding it a model instead fixes the issue.
`hurdle` and `zeroinfl` models would still fall prey to this trap, because there is some code to drop offsets that is `terms`-specific.
``` r
mod <- lm(mpg ~ factor(cyl), data = mtcars)
nd <- structure(list(cyl = structure(2:3, .Label = c("4", "6", "8"), class = "factor")), out.attrs = list( dim = c(cyl = 2L), dimnames = list(cyl = c("cyl=6", "cyl=8"))), class = "data.frame", row.names = c(NA, -2L))
nd
#>   cyl
#> 1   6
#> 2   8
get_predicted(mod, newdata = nd) |> as.data.frame() …
```
=> get_predicted_ci does not drop factor

R/format_table.R
It's "AIC weights", not "weighted AIC"
=> Fix labeling of IC weights

R/compute_variances.R, R/get_parameters.R, R/get_parameters_censored.R, R/get_parameters_others.R, R/helper_functions.R, R/utils_get_data.R, tests/testthat/test-clmm.R
use datawizard function instead
=> remove internal .gather

R/compute_variances.R, R/get_parameters.R, R/get_parameters_censored.R, R/get_parameters_others.R, R/helper_functions.R, R/utils_get_data.R, tests/testthat/test-clmm.R
=> Revert "remove internal .gather"

R/get_parameters.R
Related to https://github.com/easystats/effectsize/issues/420
Related to https://github.com/easystats/insight/issues/517
=> get standardized (b)lavaan params

R/ellipsis_info.R, R/get_predicted.R, R/get_predicted_bayesian.R, R/get_predicted_methods.R, man/ellipsis_info.Rd, man/get_predicted.Rd, tests/testthat/test-ellipses_info.R, tests/testthat/test-get_predicted.R
=> get_predicted brms

tests/testthat/test-get_data.R
An attempt to fix the currently failing test on `master` --- UNSUCCESSFUL
=> fix failing get_data test

.github/workflows/test-coverage.yml, DESCRIPTION, tests/testthat/test-logistf.R
Follow up of #579, I test things in a PR because codecov can't run on my fork
=> add codecov and exclude problematic tests

.github/workflows/R-check.yaml, .github/workflows/pkgdown.yml, .github/workflows/render-readme.yml
https://github.com/easystats/easystats/issues/200
=> update to gha v2

R/get_parameters_others.R
Issue #605 test failure
I might want to refactor this eventually, but it should work for now.
=> Issue #605: failing test get_parameters.marginaleffects

R/get_modelmatrix.R, tests/testthat/test-get_modelmatrix.R
PR for Issue #612 
The test suite segfaults on my computer (certainly my fault), so it is extra important to way for all the CI tests to show green.
=> pad factors in get_modelmatrix()

R/get_statistic.R, tests/testthat/test-coxph.R
Problem reported here: https://github.com/vincentarelbundock/modelsummary/issues/547
Might need a fix in `parameters` as well.
=> get_statistic.coxph returns wrong values

DESCRIPTION, NEWS.md, R/get_predicted_se.R, tests/testthat/test-get_predicted.R
Fixes get_predicted_se() for models with matrix-response
=> fix get_predicted_se for matrix response

README.rmd
https://github.com/easystats/easystats/issues/271
=> Add lifecycle badge

DESCRIPTION, NEWS.md, R/export_table.R, R/format_table.R
=> use type="width" with nchar

R/find_parameters_other.R, R/get_parameters_others.R, tests/testthat/test-marginaleffects.R
https://github.com/vincentarelbundock/marginaleffects/issues/495
=> marginaleffects repo issue 495

R/get_data.R, R/utils_get_data.R, tests/testthat/test-get_data.R
=> Problems with `get_data()` in `testthat` environments

DESCRIPTION, NEWS.md, R/get_predicted_args.R, R/get_predicted_ci_zeroinflated.R, R/get_predicted_mixed.R, tests/testthat/test-glmmTMB.R
=> Revdep issues with glmmTMB

DESCRIPTION, NEWS.md, R/utils_get_data.R, tests/testthat/test-get_data.R
=> Fixes #689

R/get_modelmatrix.R, tests/testthat/test-get_datagrid.R, tests/testthat/test-get_modelmatrix.R
=> Issue #693

DESCRIPTION, NEWS.md, R/get_datagrid.R, tests/testthat/test-get_datagrid.R, tests/testthat/test-glmmTMB.R, tests/testthat/test-lme.R
=> Fixes #695 (get_datagrid() does not preserve all factor levels)

R/get_transformation.R
Were missing for `log2` and `log10`
=> Add missing inv-trans

R/utils_get_data.R, tests/testthat/test-htest.R
=> More consistant data structure for data recovered from htests

tests/testthat.R, tests/testthat/test-MCMCglmm.R, tests/testthat/test-censReg.R, tests/testthat/test-get_data.R, tests/testthat/test-get_modelmatrix.R, tests/testthat/test-ivreg_AER.R, tests/testthat/test-mmrm.R, tests/testthat/test-survreg.R, tests/testthat/test-tobit.R
- https://github.com/easystats/easystats/issues/350
- https://github.com/easystats/easystats/issues/343
=> Test cleanup

DESCRIPTION, NEWS.md, R/get_weights.R, tests/testthat/test-get_weights.R
=> GLM family = binomial, error with a continuous predictor

DESCRIPTION, NEWS.md, R/utils_model_info.R, tests/testthat/test-gee.R
=> `model_info()` fails for *gee* models

DESCRIPTION, NEWS.md, R/get_data.R, tests/testthat/test-get_data.R
=> more stable get_data() for lavaan

NEWS.md, R/find_response.R, tests/testthat/test-brms.R, tests/testthat/test-brms_aterms.R
=> Fix aterms in brms-responses

R/format_table.R
=> Simplify code in `format_table()` to extract pretty names

DESCRIPTION, NEWS.md, R/find_terms.R, R/is_nested_models.R, man/find_terms.Rd, man/is_nested_models.Rd, tests/testthat/test-brms.R, tests/testthat/test-find_terms.R, tests/testthat/test-logistf.R
=> `find_terms` can't "look" inside parentheses

DESCRIPTION, NEWS.md, R/get_predicted_args.R, R/model_info.R, man/model_info.Rd, tests/testthat/test-get_predicted.R
=> get_predict(predict = "link") for `gaussian(link = "log")` models

.github/SUPPORT.md
Related to https://github.com/easystats/easystats/issues/265
=> Add "Getting help" page 

CRAN-SUBMISSION, DESCRIPTION, NEWS.md, cran-comments.md
=> CRAN submission 0.19.5 (hotfix)

DESCRIPTION, NEWS.md, R/format_value.R, R/n_obs.R, R/utils_model_info.R, tests/testthat/test-ggeffects.R, tests/testthat/test-model_info.R
=> glm model misreported as bernoulli

DESCRIPTION, NEWS.md, R/clean_names.R, R/find_formula.R, R/find_predictors.R, R/find_random.R, R/helper_functions.R, tests/testthat/test-brms_gr_random_effects.R
=> `brms::gr()` is not supported

R/compute_variances.R, R/null_model.R
=> ICC for brms Beta model: returning NA

DESCRIPTION, R/find_predictors.R, tests/testthat/test-mgcv.R
=> `find_predictors()`: false positives with some user inputs in GAM splines

DESCRIPTION, NEWS.md, R/apply_table_theme.R, inst/WORDLIST, man/export_table.Rd, tests/testthat/test-apply_table_theme.R
=> Fix `apply_table_theme()`

DESCRIPTION, NEWS.md, R/clean_names.R, R/helper_functions.R, R/utils_get_data.R, tests/testthat/test-GLMMadaptive.R, tests/testthat/test-brms.R, tests/testthat/test-brms_aterms.R, tests/testthat/test-clean_names.R, tests/testthat/test-format_table.R, tests/testthat/test-get_loglikelihood.R
=> `insight::find_variables()`: error with `brms` and `mm()`

R/get_varcov_sandwich.R
Very minor PR to improve the error message in `get_varcov()`
=> get_varcov_sandwich: Better error message

DESCRIPTION, NEWS.md, R/null_model.R, tests/testthat/test-null_model.R, tests/testthat/test-r2_nakagawa_poisson_zi.R
=> `null_model()` for zero-inflated models.

DESCRIPTION, NEWS.md, R/compute_variances.R, R/get_sigma.R, R/get_variances.R, man/get_variance.Rd
=> Infinite loop in icc() for some brms models

DESCRIPTION, NEWS.md, R/ellipsis_info.R, tests/testthat/test-ellipses_info.R
=> `ellipses_info()` doesn't work with `do.call()`

DESCRIPTION, NEWS.md, R/find_formula.R, R/null_model.R, tests/testthat/test-find_formula.R, tests/testthat/test-null_model.R
=> `get_variance()` and `null_model()`  functions not working depending on the way you call the objects of your model

DESCRIPTION, NEWS.md, R/find_transformation.R, R/get_loglikelihood.R, R/get_predicted_ci_zeroinflated.R, R/get_transformation.R, man/find_transformation.Rd, tests/testthat/test-find_transformation.R, tests/testthat/test-get_loglikelihood.R, tests/testthat/test-get_transformation.R
=> Handle Box-Cox transformation

DESCRIPTION, R/export_table.R, inst/WORDLIST, tests/testthat/_snaps/export_table.md, tests/testthat/test-export_table.R, vignettes/export.Rmd
=> Fix `table_width = "auto"` for very wide first column

DESCRIPTION, NEWS.md, R/format_value.R, R/get_data.R, man/format_value.Rd, tests/testthat/test-get_data.R
=> insight::get_data issue with subset argument provided via eval(parse(text=...))

DESCRIPTION, NEWS.md, R/compute_variances.R, R/find_parameters_bayesian.R, R/get_sigma.R, R/helper_functions.R, tests/testthat/test-brms.R
=> Discrepancy in residual variance between VarCorr() and get_variance_residual()

R/clean_parameters.R, R/find_parameters_bayesian.R, R/helper_functions.R, R/utilities.R
=> reduce usage of `perl = TRUE` in regex, where possible

DESCRIPTION, NEWS.md, R/find_transformation.R, tests/testthat/test-find_transformation.R
=> find_transformation() returning multiple values

DESCRIPTION, NEWS.md, R/find_predictors.R, R/find_terms.R, R/find_variables.R, R/has_intercept.R, R/model_info.R, tests/testthat/test-brms_von_mises.R
=> modelbased struggles with brms' Von Mises family

DESCRIPTION, NEWS.md, R/get_datagrid.R, inst/WORDLIST, tests/testthat/test-get_datagrid.R
Fixes https://github.com/easystats/modelbased/issues/285
=> Should we add `allow.new.levels=TRUE` by default?

R/find_formula.R, R/get_predicted.R, R/get_predicted_args.R, R/get_predicted_bayesian.R, R/helper_functions.R, man/get_predicted.Rd, tests/testthat/test-get_predicted.R
https://github.com/easystats/modelbased/pull/287
=> `get_predicted()` supports dpar

.github/CONTRIBUTING.md, DESCRIPTION, NEWS.md, R/get_predicted.R, R/get_predicted_bayesian.R, tests/testthat/test-get_predicted.R
=> get_predicted() with categorical: extra Row column

DESCRIPTION, NEWS.md, R/find_formula.R, tests/testthat/test-mgcv.R
=> find_predictors() returns null for multinomial gam models

DESCRIPTION, NEWS.md, R/find_transformation.R, R/get_transformation.R, man/find_transformation.Rd, tests/testthat/test-find_transformation.R, tests/testthat/test-get_transformation.R
=> get_transformation Ignores Logarithmic Base

DESCRIPTION, NEWS.md, R/find_random.R, R/find_random_slopes.R
names from auxiliary components
=> `find_random()` and `find_random_slopes()` now also extract random effects

DESCRIPTION, NEWS.md, R/clean_parameters.R, tests/testthat/test-clean_parameters.R
=> Fix `clean_parameters()` for auxiliary components of brms-models

DESCRIPTION, tests/testthat/test-r2_nakagawa_poisson_zi.R
https://github.com/glmmTMB/glmmTMB/issues/1132#issuecomment-2761895637
=> Run tests on glmmTMB devel

DESCRIPTION, NEWS.md, R/export_table.R, R/format_table_glue.R, man/export_table.Rd, tests/testthat/test-export_table.R
=> display() improvements

DESCRIPTION, NEWS.md, R/find_auxiliary.R, R/get_predicted_args.R, man/find_auxiliary.Rd, man/insight-package.Rd, tests/testthat/test-brms.R
=> predict non-standard brms parameters

DESCRIPTION, R/clean_parameters.R, R/find_auxiliary.R, R/find_parameters_brms.R, man/find_auxiliary.Rd, tests/testthat/test-brms.R
=> modelbased::estimate_grouplevel() misses dpars from ZOIB

DESCRIPTION, R/find_parameters_brms.R
=> Error in clean_params()

DESCRIPTION, R/get_predicted_args.R
=> get_predicted(predict="mu") doesn't work

DESCRIPTION, NEWS.md, R/find_parameters_bayesian.R, R/find_parameters_brms.R, R/get_parameters_bayesian.R, R/helper_functions.R, man/find_parameters.BGGM.Rd, man/get_parameters.BGGM.Rd, tests/testthat/test-brms.R
=> Make parameters() for brms faster

DESCRIPTION, tests/testthat/test-lmer.R
=> Unit level DF for Satterthwaite and Kenward-Roger

DESCRIPTION, NEWS.md, R/find_formula.R, R/get_priors.R, R/print_parameters.R, inst/WORDLIST, man/print_parameters.Rd, tests/testthat/test-clean_parameters.R, tests/testthat/test-compact-list.R, tests/testthat/test-dbart.R
=> `dbarts::bart2(outcome ~ .)` with `get_data()` does not return all variables

DESCRIPTION, NEWS.md, R/export_table.R, R/find_random.R, R/find_response.R, tests/testthat/test-brms.R
=> `insight::find_random()` with multivariate `brms`

DESCRIPTION, NEWS.md, R/model_info.R, tests/testthat/test-betareg.R
=> get_datagrid() (and by extension modelbased) support for betareg

DESCRIPTION, NEWS.md, R/find_formula.R, tests/testthat/test-mhurdle.R
=> `mhurdle`: `find_formula` error
